apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres_user }}
  POSTGRES_PASSWORD: {{ .Values.postgres_password }}
  POSTGRES_DB: {{ .Values.postgres_db }}
  
  DB_HOST: {{ .Values.db_host }}
  DB_USER: {{ .Values.db_user }}
  DB_PASS: {{ .Values.db_pass }}
  DB_NAME: {{ .Values.db_name }}
  DB_PORT: {{ .Values.db_port }}

  AWS_ACCESS_KEY_ID: {{ .Values.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws_secret_access_key }}