apiVersion: v1
kind: PersistentVolume 
metadata:
  name: {{ .Values.persistence.name }}
  labels:
    type: {{ .Values.persistence.type }}
    app: {{ .Values.service.db.name }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath: 
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain 
