apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: {{ .Values.persistence.name }}-claim
  labels:
    app: {{ .Values.service.db.name }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - {{ .Values.persistence.accessMode }} 
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
