apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-frontend
spec:
  selector:
    matchLabels:
      app: ui-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-frontend
    spec:
      containers:
        - name: ui-frontend
          image: simsti97/webui:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
