replicaCount: 1

image: 
  backend: simsti97/api:latest
  db: simsti97/postgres-db:latest
  frontend: simsti97/webui:latest

service:
  backend:
    name: api-service
    type: NodePort
    port: 80
  db:
    name: fullstack-postgres
    type: NodePort
    port: 5432
  frontend:
    name: ui-service
    type: NodePort
    port: 80

env:
  secretName: postgres-secret
  postgres_user: ""
  postgres_password: ""
  postgres_db: ""
  db_host: ""
  db_user: ""
  db_pass: ""
  db_name: ""
  db_port: ""
  aws_access_key_id: ""
  aws_secret_access_key: ""

resources:
  request: 
    cpu: 0.5
    memory: 512Mi
  limit: 
    cpu: 1
    memory: 1Gi

persistence: 
  enabled: true
  name: postgres-pv-volume
  type: local
  storageClass: manual 
  accessMode: ReadWriteMany
  size: 5Gi

nodePort: 
  backend: 30001
  frontend: 30002
