name: docker-hub Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./task20/api
          push: true
          tags: ${{ secrets.DOCKER_IMAGE_TAG }}/api:latest

      - name: Build and push Web UI Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./task20/webui
          push: true
          tags: ${{ secrets.DOCKER_IMAGE_TAG }}/webui:latest
