name: Helm CI/CD Pipeline

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install conntrack
      run: sudo apt-get install -y conntrack
    - name: Install Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
        && chmod +x minikube
        sudo mkdir -p /usr/local/bin/
        sudo install minikube /usr/local/bin/

    - name: Start Minikube
      run: minikube start --driver=none --kubernetes-version=v1.20.0

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.5.3

    - name: Deploy to Minikube
      run: |
        helm upgrade --install fullstack-chart ./task26_helm_cicd/fullstack --namespace default \
          --set postgres_user=${{ secrets.POSTGRES_USER }} \
          --set postgres_password=${{ secrets.POSTGRES_PASSWORD }} \
          --set postgres_db=${{ secrets.POSTGRES_DB }} \
          --set db_host=${{ secrets.DB_HOST }} \
          --set db_user=${{ secrets.DB_USER }} \
          --set db_pass=${{ secrets.DB_PASS }} \
          --set db_name=${{ secrets.DB_NAME }} \
          --set db_port=${{ secrets.DB_PORT }} \
          --set aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }} \
          --set aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
